-- CreateTable
CREATE TABLE "RateSettingsDefault" (
    "id" TEXT NOT NULL,
    "finacialReserveFee" DOUBLE PRECISION NOT NULL DEFAULT 0.15,
    "AdvanceFee" DOUBLE PRECISION NOT NULL DEFAULT 0.06,
    "gatewayCreditFixed" DOUBLE PRECISION NOT NULL DEFAULT 1.49,
    "gatewayCreditPercents" DOUBLE PRECISION[] DEFAULT ARRAY[0.0899, 0.0899, 0.1499, 0.1499, 0.1979, 0.1979, 0.1979, 0.2799, 0.2799, 0.2799, 0.2799, 0.2799, 0.2799]::DOUBLE PRECISION[],
    "gatewayPixFixed" DOUBLE PRECISION NOT NULL DEFAULT 4.99,
    "gatewayPixPercents" DOUBLE PRECISION[] DEFAULT ARRAY[0.02]::DOUBLE PRECISION[],
    "gatewayBilletFixed" DOUBLE PRECISION NOT NULL DEFAULT 3.99,
    "gatewayBilletPercents" DOUBLE PRECISION[] DEFAULT ARRAY[0.0199]::DOUBLE PRECISION[],
    "withdrawalFee" DOUBLE PRECISION NOT NULL DEFAULT 4,
    "acquirer" TEXT NOT NULL DEFAULT 'transfeera',
    "acquirerPix" TEXT NOT NULL DEFAULT 'iugu',
    "acquirerCard" TEXT NOT NULL DEFAULT 'abmex',
    "acquirerBillet" TEXT NOT NULL DEFAULT 'abmex',
    "reservePix" DOUBLE PRECISION NOT NULL DEFAULT 0.1,
    "reservePixDay" INTEGER NOT NULL DEFAULT 180,
    "reserveCard" DOUBLE PRECISION NOT NULL DEFAULT 0.1,
    "reserveCardDay" INTEGER NOT NULL DEFAULT 180,
    "reserveBillet" DOUBLE PRECISION NOT NULL DEFAULT 0.1,
    "reserveBilletDay" INTEGER NOT NULL DEFAULT 180,
    "anticipationDays" INTEGER NOT NULL DEFAULT 2,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RateSettingsDefault_pkey" PRIMARY KEY ("id")
);
